# Generated by Django 6.0.6 on 2026-06-17 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staffinvitetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLockoutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lockout_level', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_lockout_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_lockout_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lockout_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_lockout_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_session_records',
                'unique_together': {('user', 'ip_address', 'user_agent')},
            },
        ),
    ]
