# Generated by Django 5.2.15 on 2026-07-02 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_bidder_set_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bidder', 'submitted_at'], name='bid_bidder_submitted_idx'),
        ),
    ]
