"""MFA (TOTP) API — SFR-02b / NFSR-AU-01 / NFSR-AU-04 / NFSR-AC-02 (diagram: svc_mfa)."""
import base64
import io
import logging

import qrcode
from django.contrib.auth import get_user_model
from django.contrib.auth import login as django_login
from django.contrib.auth.signals import user_login_failed
from django_otp.plugins.otp_totp.models import TOTPDevice
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from core.cross_cutting.audit import log_action, device_fingerprint as _device_fingerprint

from ..business.mfa_service import log_mfa_event
from ..business.session_manager import get_client_ip, notify_new_device_or_location
from .serializers import UserProfileSerializer

logger = logging.getLogger("securebid")

User = get_user_model()


class MFAStatusView(APIView):
    """Return whether the authenticated user has MFA enrolled."""

    permission_classes = [IsAuthenticated]

    def get(self, request):
        enrolled = TOTPDevice.objects.filter(
            user=request.user, confirmed=True
        ).exists()
        return Response({"enrolled": enrolled})


class MFAEnrolView(APIView):
    """Begin MFA enrolment: generate a TOTP secret and return a QR code.

    The secret is generated by django-otp using os.urandom (CSPRNG) and stored
    in otp_totp_totpdevice, protected at rest by Supabase AES-256 (NFSR-AU-01).
    The device is left unconfirmed until the user verifies their first code.
    """

    permission_classes = [IsAuthenticated]

    def get(self, request):
        # Drop any previous unconfirmed device so enrolment is idempotent.
        TOTPDevice.objects.filter(user=request.user, confirmed=False).delete()

        device = TOTPDevice.objects.create(
            user=request.user,
            name=request.user.email,
            confirmed=False,
        )

        qr = qrcode.QRCode()
        qr.add_data(device.config_url)
        qr.make(fit=True)
        img = qr.make_image()
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        qr_b64 = base64.b64encode(buf.getvalue()).decode()

        return Response({"qr_code": qr_b64})


class MFAEnrolConfirmView(APIView):
    """Complete MFA enrolment by verifying the user's first TOTP code."""

    permission_classes = [IsAuthenticated]

    def post(self, request):
        otp_code = request.data.get("otp_code", "").replace(" ", "")

        device = TOTPDevice.objects.filter(
            user=request.user, confirmed=False
        ).first()

        if device is None:
            return Response(
                {"detail": "No pending MFA setup found. Please start again."},
                status=400,
            )

        if not device.verify_token(otp_code):
            user_login_failed.send(
                sender=request.user.__class__,
                credentials={"username": request.user.email},
                request=request,
            )
            return Response({"detail": "Invalid code. Please try again."}, status=400)

        device.confirmed = True
        device.save(update_fields=["confirmed"])

        log_mfa_event(request.user, "mfa_enrolled", request)
        logger.info("MFA enrolled for user %s", request.user.email)

        return Response({"detail": "MFA enabled successfully."}, status=200)


class MFAUnenrolView(APIView):
    """Disable MFA by removing the user's TOTP device."""

    permission_classes = [IsAuthenticated]

    def post(self, request):
        deleted, _ = TOTPDevice.objects.filter(user=request.user).delete()

        if not deleted:
            return Response(
                {"detail": "MFA is not enabled on this account."}, status=400
            )

        log_mfa_event(request.user, "mfa_disabled", request)
        logger.info("MFA disabled for user %s", request.user.email)

        return Response({"detail": "MFA disabled successfully."}, status=200)


class MFALoginVerifyView(APIView):
    """Complete a pending MFA login by verifying the TOTP code.

    The user's identity was already confirmed by password in LoginView.
    Only the session token grants access — the session is not fully
    authenticated until this step succeeds.

    Invalid codes are counted toward the django-axes lockout threshold
    (NFSR-AU-04). The TOTPDevice.last_t column prevents token replay within
    the same 30-second window (SFR-02b).
    """

    permission_classes = [AllowAny]

    def post(self, request):
        user_id = request.session.get("_mfa_pending_user_id")
        backend = request.session.get("_mfa_pending_backend")

        if not user_id:
            return Response(
                {"detail": "No pending MFA verification. Please log in again."},
                status=400,
            )

        try:
            user = User.objects.get(pk=user_id)
        except User.DoesNotExist:
            return Response(
                {"detail": "Session expired. Please log in again."}, status=400
            )

        ip = get_client_ip(request)
        ua = request.META.get("HTTP_USER_AGENT", "")
        otp_code = request.data.get("otp_code", "").replace(" ", "")
        device = TOTPDevice.objects.filter(user=user, confirmed=True).first()

        if device is None or not device.verify_token(otp_code):
            user_login_failed.send(
                sender=user.__class__,
                credentials={"username": user.email},
                request=request,
            )
            try:
                log_action(
                    user=user,
                    action="mfa_login_failed",
                    resource_type="User",
                    resource_id=user.id,
                    ip_address=ip,
                    user_agent=ua,
                    device_fingerprint=_device_fingerprint(ip, ua),
                    role="staff" if user.is_staff else "user",
                    request_method=request.method,
                    endpoint_path=request.path,
                    metadata={"reason": "invalid_otp"},
                )
            except Exception:
                pass
            return Response({"detail": "Invalid code. Please try again."}, status=400)

        # Clear pending markers before elevating to a full session.
        del request.session["_mfa_pending_user_id"]
        del request.session["_mfa_pending_backend"]

        user.backend = backend
        django_login(request, user)
        notify_new_device_or_location(request, user)

        try:
            log_action(
                user=user,
                action="mfa_login_success",
                resource_type="User",
                resource_id=user.id,
                ip_address=ip,
                user_agent=ua,
                device_fingerprint=_device_fingerprint(ip, ua),
                role="staff" if user.is_staff else "user",
                request_method=request.method,
                endpoint_path=request.path,
                metadata={"session_key": request.session.session_key},
            )
        except Exception:
            pass

        return Response(UserProfileSerializer(user).data, status=200)
